### ISSUE TITLE
Use factory.local as domain in the environment

### ISSUE THREAD

**Issue by iranzo** [rh-ecosystem-edge/ztp-pipeline-relocatable#356]

**Comment by fbac** [comment]
Summarizing here what was talked offline:

- We'll use this change to address the changes proposed in https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/issues/359

- Because of it, we'll be removing the trailing "-cluster" suffix in the following files:
```
.github/workflows/testing-pr.yml
deploy-edgecluster/render_edgecluster.sh
hack/env
hack/deploy-hub-local/build-egecluster.sh
hack/deploy-hub-local/create-vm.yml
hack/deploy-hub-local/create-vm-sno.yml
hack/deploy-hub-local/lab-dns-internal.sh
hack/deploy-hub-local/lab-dns-external.sh
hack/deploy-hub-local/ansible/tasks/files
```

- All the tests will be passed in the same change to avoid multiple points of failure and debug while we have this issue running and being tested with every change at once.
